### ISSUE TITLE
Timeout since Version 1.4.4

### ISSUE THREAD

**Issue by kawild** [ndortega/Oxygen.jl#148]
Since Version 1.4.4 Oxygen doesn´t seem to work correctly without any code changes on Linux and Windows.
No error shows up in the log but I get a timout for every address.
Even opening /docs in the browser is not working.

Switching back to 1.4.3 and erverything is fine.

**Comment by ndortega** [comment]
Hi @kawild, 

Can you provide a code snippet of the server you're trying to run along with any relevant configuration on your setup? I've set up a basic server on both mac and windows and haven't encountered a timeout issue.

**Comment by kawild** [comment]
I found that excluding the following middleare from serve() solves the problem on 1.4.6:

```
function gzipMiddleware(handler)
    return function (req::HTTP.Request)
        response = handler(req)
        response.status == 200 || return response

        if HTTP.headercontains(req, "Accept-Encoding", "gzip")
            HTTP.setheader(response, "Content-Encoding" => "gzip")
            compressedbody = transcode(GzipCompressor, response.body)
            response.body = compressedbody
        end

        return response
    end
end

```

I can replicate this on a basic server.

**Comment by ndortega** [comment]
Thanks for the snippet, this helped me isolate the bug. As of a couple of updates ago I started automatically calculating and injecting the `Content-Length` Header into every HTTP.Response coming out of Oxygen. 

In theory, this is a good practice that helps consumers read responses faster. But when we use middleware that modifies the content of a response after it comes out of a request handler the old `Content-Length` header is no longer accurate and will break responses. **To fix this issue, you'll just need to overwrite the old value with the updated length like in the snippet below**. 

Going forward I think I'm going to release an update where I turn this off, so that all HTTP.Responses are returned as is without any modifications so we don't encounter content length issues like this in the future.

```julia
function gzipMiddleware(handler)
    return function (req::HTTP.Request)
        response = handler(req)
        response.status == 200 || return response

        if HTTP.headercontains(req, "Accept-Encoding", "gzip")
            compressedbody = transcode(GzipCompressor, response.body)
            response.body = compressedbody
            # need to overwrite the Content-Length header which is automatically set, because the body has changed
            HTTP.setheader(response, "Content-Length" => string(sizeof(compressedbody)))
            HTTP.setheader(response, "Content-Encoding" => "gzip")
        end

        return response
    end
end
```

**Comment by ndortega** [comment]
I've updated the default behavior in the latest pr. Please reopen this issue if you're still encountering issues

**Comment by ndortega** [comment]
@kawild

As an aside, if you want to compress files for individual routes without using middleware you can do so using the `loadfile` kwarg in the `file()` function renderer

```julia
function load(filepath::String) :: Vector{UInt8}
    return transcode(GzipCompressor, read(filepath))
end

get("/compress") do
    file("./static/index.html", loadfile=load, headers=["Content-Encoding" => "gzip"])
end
```
