### ISSUE TITLE
Static CSS isn't served

### ISSUE THREAD

**Issue by joshday** [ndortega/Oxygen.jl#64]
I'm trying to use `@staticfiles` to serve an html file and some css.  I can load `index.html`, but `styles.css` is nowhere to be found.  Am I missing something obvious?

- `static/index.html`

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    Hi there
</body>
</html>
```

- `static/styles.css`

```css
html {
    color : blue;
}
```

- My code:

```Julia
using Oxygen

@staticfiles "static" ""

serve()
```

**Comment by ndortega** [comment]
Hi @joshday,

Thanks for bringing this issue up! To answer your question, no you're not crazy - your setup looks fine. Oxygen is returning the wrong MIME type when it tries to load that CSS file. 

Internally I've been using the [HTTP.sniff()](https://docs.juliahub.com/HTTP/zXWya/1.3.3/reference/#HTTP.Sniff.sniff) function to automatically detect MIME types for mounted files. The problem is that it's returning `text/plain` instead of `text/css`. 

Below is an example of this mime-type mismatch:
```julia
css_string = "
  html {
    color : blue;
  }
"
println(HTTP.sniff(css_string)) # => text/plain
```

I should probably raise an issue in the HTTP.jl repo to fix this problem. Or I may just use the file extensions to determine the mime type instead of relying on HTTP.sniff(). In the meantime, you can manually "mount" your static files to get your CSS working: 

```julia
using Oxygen
using HTTP

@get "/static/index.html" function()
    file("static/index.html")
end

@get "/static/styles.css" function()
    content = file("static/styles.css")
    headers = ["Content-Type" => "text/css"]
    HTTP.Response(200, headers, body=content)
end

serve()
```

By the way, you can call the mounting macros with parenthesis. Both arguments are optional, so you don't have to pass an empty string as a second argument. Here's an example:

```julia
using Oxygen

# in this case we look in the 'static' folder for files and serve them under '/static/' endpoint
@staticfiles("static")

serve()
```

**Comment by joshday** [comment]
Thanks for the detailed response and workaround!

p.s. This package is awesome.

**Comment by ndortega** [comment]
No problem at all! I'm glad I could help
