### ISSUE TITLE
Embedding routes within a module via `__init__()`

### ISSUE THREAD

**Issue by mkitti** [ndortega/Oxygen.jl#73]
On the forums, I encountered some confusion about a `@get` route at the top level of a package module:
https://discourse.julialang.org/t/difference-between-include-and-using/87795

The problem with putting the routes at the top level of the module is that this is only invoked during precompilation. It is not invoked when the module is loaded.

For the routes to be loaded at module initialization, the routes should be declared from `__init__` or some function called from `__init__()`:

```julia
module OxygenExample
using Oxygen
using HTTP


function runserver()
    serve()
end

function __init__()
    @get "/greet" function(req::HTTP.Request)
        return "hello world!"
    end
    # routes may also be contained in src/main.jl
    include(joinpath(@__DIR__,"main.jl"))
end

end # module OxygenExample
```

**Comment by ndortega** [comment]
Thanks @mkitti  for opening this issue, this was the first Oxygen.jl issue on the Julia discourse forums. 

Could you clarify the ask? Did you want to add this to the docs? Or are you looking for an alternative way to declare routes? I could look into adding additional route registering functions with a do-end block syntax (same as Genie.jl), the downside is that the first call to each endpoint would be slower because we'd need to store the parsing & mapping strategy at runtime.

The routing macros have the following benefits:
- Provide us a nice syntax to declare routes
- Allow us to generate the parsing logic at build time to parse & map incoming parameters to function handlers with minimal overhead.

**Comment by mkitti** [comment]
Mainly documenting this would be great.

I'm also thinking about if the macros could be used in a way to create routes during the precompilation phase, but then have them activated on modules load via `__init__`, but I'm not sure if I have the bandwidth to think about this at the moment.

**Comment by ndortega** [comment]
Awesome, I can definitely add that to the docs in the next update. I'll keep this issue open until then. 

And to your second point, that'd be cool but difficult to implement. As you know, the whole point of macros is to get executed at the precompilation phase.
