### ISSUE TITLE
Globals in core

### ISSUE THREAD

**Issue by jariji** [ndortega/Oxygen.jl#74]
Currently there are global variables for the server and router. This architecture is sometimes convenient but also makes it harder to test and parallelize since there are shared variables and harder to see what's going on since functions can pull the server and router out of the air. I wonder if an alternate architecture would be possible, where I create my own server and router, and then use them by passing those objects to functions explicitly.

**Comment by ndortega** [comment]
Hi @jariji , 

Managing the globals internally makes the api less noisy and simpler to use. But I can overload or parameterize the server() and routing macros to take server and router objects. 

Can you walk me through your use case? I could see the benefit of managing your own server but I'm not seeing too many benefits of managing the Router. This package was made to simplify registering functions and paths to the internal Router.

**Comment by jariji** [comment]
> Managing the globals internally makes the api less noisy and simpler to use. But I can overload or parameterize the server() and routing macros to take server and router objects.

I didn't quite mean mentioning the server at the point where an endpoint is declared. Rather I wast thinking of creating some endpoints and then adding them to the server in a similar style to [Rust's Rocket](https://rocket.rs/v0.5-rc/guide/overview/#mounting) and [Python's Starlette](https://www.starlette.io/routing/#submounting-routes):

```jl
# Julia 

@get "/world" function world(req)
  "world"
end

server = Server(routes=[Mount("/hello", routes=[world]])
serve(server)
```

Starlette then allows, for example, using multiple routers to support [host-based routing](https://www.starlette.io/routing/#host-based-routing):

```py
# Python 

site = Router()  # Use eg. `@site.route()` to configure this.
api = Router()  # Use eg. `@api.route()` to configure this.
news = Router()  # Use eg. `@news.route()` to configure this.

routes = [
    Host('api.example.org', api, name="site_api")
]

app = Starlette(routes=routes)

app.host('www.example.org', site, name="main_site")

news_host = Host('news.example.org', news)
app.router.routes.append(news_host)
```

In general I like the functional style where objects are built up explicitly rather than reaching out into invisible globals -- but admittedly this may be a matter of personal taste.

**Comment by ndortega** [comment]
No argument here, managing the global state internally absolutely makes testing more difficult from my end. Switching the syntax to a more Starlette approach would make my life much easier as a maintainer. 

Granted, a syntactical change as large as this would require a lot of community support before I'd implement it. I feel most people like using this package due to the "zero config" needed to spin up a web server. 

Now host-based routing is an interesting feature, and one I could add by utilizing the `router()` HOF, which I would argue is even more straightforward than Starlette's approach. 

In my mind it'd look something like the following for a single endpoint:
```julia
@get router("/world", host="www.example.org") function(req)
  "world"
end
```

Or you could apply host based routing on multiple endpoints by reusing the `router()` HOF.

```julia

worldrouter = router("/world", host="www.example.org")

@get worldrouter("/northamerica") function(req)
  "northamerica"
end

@get worldrouter("/europe") function(req)
  "europe"
end
```

**Comment by ndortega** [comment]
@ExpandingMan 

I closed this primarily because I didn't receive any feedback on the host-based routing feature. I'm all for new features, but I'm not gonna spend time on them unless people actually want them. 

I also closed this because this thread is no longer about the original issue: sweeping architectural changes to the package

**Comment by ExpandingMan** [comment]
Fair enough, I'm not about to tell you how to govern the package.  For whatever it's worth, I'd still be very much interested in this if anybody ever wanted to do the overhaul.

**Comment by ndortega** [comment]
@ExpandingMan 
If you can find a way to provide this alternate project setup without impacting the current flow, I'd be more than happy to add it in. I want this to be a tool for the community, in fact I've accepted every PR that's been raised by outside sources. They sometimes needed a little work, but they've all been merged in the end. 

We can always just open up a poll to see what people are thinking on this issue. I could very well be in the minority on this
