### ISSUE TITLE
rest noob question: how do i have an endpoint return an image?

### ISSUE THREAD

**Issue by anandijain** [ndortega/Oxygen.jl#84]
i have seen apis that have endpoints that return pictures before, and i'd like to do this.

i'm sure this is straightforward (setting Content-Type is what i'm seeing online), but i'm stumbling around a bit.

i'd be happy to contribute a PR as an example if anyone would find that useful

**Comment by anandijain** [comment]
wow the answer is exactly as I would have assumed. I love Oxygen.jl, it just works!

```julia
@get "/plot" function (req)
    plt = plot(1:10, rand(10))
    io = IOBuffer()
    png(plt, io)
    HTTP.Response(200, ["Content-Type"=>"image/png"]; body=take!(io))
end
```

**Comment by ndortega** [comment]
Hey @anandijain, thanks for the kind words! 
You've been with this project since day one, so I'm glad it's still helping you solve problems. Now regarding your solution, that's probably the clearest & most performant way you could write your endpoint - but there is another way you could write it. Inside the default serializer I use [HTTP.sniff](https://juliaweb.github.io/HTTP.jl/v0.6/index.html#HTTP.sniff) on the body of each request to automatically detect the correct mimetype and set the headers in the response.

Here's another way you could write that function:
```julia
@get "/plot" function (req)
    plt = plot(1:10, rand(10))
    io = IOBuffer()
    png(plt, io)
    take!(io) # if this part fails then try returning this instead: String(take!(io))
end
```
